apiVersion: apps/v1
kind: Deployment
metadata:
  name: lindda1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lindda1
  template:
    metadata:
      labels:
        app: lindda1
    spec:
      containers:
      - image: okteto.dev/lindda1:latest
        name: lindda1
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "ab316239-970b-4ded-80e6-ed489382a33d"
        - name: Vless_Path
          value: "/vl5sdfdg55"
        - name: Vmess_UUID
          value: "ab316239-970b-4ded-80e6-ed489382a33d"
        - name: Vmess_Path
          value: "/vm66cvfgfh66"
        - name: Share_Path
          value: "/v2link"
