apiVersion: v1
kind: Service
metadata:
  name: lindda1
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP  
  ports:
  - name: "lindda1"
    port: 8080
  selector:
    app: lindda1
